### ISSUE TITLE
Date format change causes --mode verify to fail

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#40]
Continuation to 
- #39 

now that running in `--mode verify` we get

```
2024-03-30T12:21:03-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000051/draft>:
  + Exception Group Traceback (most recent call last):
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/aioutil.py", line 177, in dowork
  |     outp = await func(inp)
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/datasetter.py", line 159, in update_dandiset
  |     changed = await self.sync_dataset(
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/datasetter.py", line 203, in sync_dataset
  |     await syncer.sync_assets()
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/syncer.py", line 77, in sync_assets
  |     report = await async_assets(
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/asyncer.py", line 499, in async_assets
  |     async with (
  |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/asyncer.py", line 257, in process_blob
    |     raise UnexpectedChangeError(
    | backups2datalad.util.UnexpectedChangeError: Dandiset 000051: Metadata for asset pons8-yo_16xdownsampled.nwb was changed/added but draft timestamp was not updated on server:
    | 
    | Metadata diff:
    | 
    | --- old-metadata
    | +++ new-metadata
    | @@ -1,6 +1,6 @@
    |  asset_id: 203fdd15-60d6-41c4-b964-3439163e4e3a
    |  blob: cd0cec83-c6e6-454a-950b-da2582b9bd30
    | -created: '2021-07-03T04:16:36.473127+00:00'
    | +created: '2021-07-03T04:16:36.473127Z'
    |  metadata:
    |    '@context': https://raw.githubusercontent.com/dandi/schema/master/releases/0.4.4/context.json
    |    access:
    | @@ -43,6 +43,6 @@
    |        schemaKey: Software
    |        url: https://github.com/dandi/dandi-cli
    |        version: 0.22.0
    | -modified: '2021-08-05T18:52:05.517987+00:00'
    | +modified: '2021-08-05T18:52:05.517987Z'
    |  path: pons8-yo_16xdownsampled.nwb
    |  size: 585926072
    | 
    | 
    +------------------------------------
```

so it is solely due to date format change.  Is it from the server or our formatting?  Are we doomed to provide "value testing" instead of string comparison for those fields ?

For now I will keep `--mode verify` cron job off

**Comment by jwodder** [comment]
@yarikoptic This is due to the timestamp format returned by the Archive changing, possibly due to the upgrade from pydantic 1.x to 2.x.

**Comment by jwodder** [comment]
@yarikoptic I can think of the following possible approaches, in roughly decreasing order of preference:

* Get the Archive to revert its timestamp format to the old format somehow

* Write & run a single-use script that sweeps through all Dandiset backups, updates the formats of the timestamp fields in `assets.json` and `dandisets.yaml`, and commits the changes

* Make `backups2datalad` convert timestamps in metadata received from the API to the old format upon deserialization, thereby avoiding any changes to the `assets.json` and `dandisets.yaml` files in the backups

**Comment by yarikoptic** [comment]
- I don't think reversion is worthwhile this late: we would end up in inconsistent state

- what about the last one, but convert to new format upon loading if old format is detected?  and do we explicitly specify format of datetime/zone explicitly ?  may be it could be just at the point of comparison?

**Comment by jwodder** [comment]
@yarikoptic

Correction: Assuming the only timestamps that are being reformatted are the two fields shown in your log sample above, the change is actually due to dandi-cli now using pydantic 2.x, as dandi-cli and `backups2datalad` use a Pydantic model for asset properties but not asset metadata.

> convert to new format upon loading if old format is detected

I assume you mean loading & converting `assets.json`.  `backups2datalad` currently just loads this by deserializing the JSON into primitive types, without any coercion of timestamp strings to `datetime` objects.

> and do we explicitly specify format of datetime/zone explicitly ? may be it could be just at the point of comparison?

The structure passed to the `assets.json` registry is a JSON-ready dict of asset properties & metadata, in which the `created` and `modified` fields are converted to strings using pydantic's default timestamp formatting.

Honestly, I do not want to do option 3.  It would mean adding functionality to `backups2datalad` that would only be useful once, after which the code would probably end up being maintained long after its applicability has passed.

**Comment by yarikoptic** [comment]
ok, should we do option 2 then?  

btw -- I do not know how/why but may be in the future we need to reprocess those .json etc files for already tagged releases? then we might need to run the script again, so having option 3. would have avoided doing anything special .

**Comment by jwodder** [comment]
@yarikoptic 

> ok, should we do option 2 then?

That's what I'd prefer.

> I do not know how/why but may be in the future we need to reprocess those .json etc files for already tagged releases?

Unless you can come up with a scenario where we would have to do that, I don't think we should concern ourselves with it.

**Comment by yarikoptic** [comment]
Ok, let's then go route 2. Please code and apply across dandisets

**Comment by yarikoptic** [comment]
> Once you approve the PR, I will run it on drogon whenever no backup cronjobs are running.

great, thank you! please run it under the same `flock` session so if cron kicks in, there is some protection from collision.

**Comment by jwodder** [comment]
@yarikoptic Timestamps updated and pushed.  Should I re-enable the "verify" cronjob now?

**Comment by yarikoptic** [comment]
sure, or may be run it on a few datasets which were changed to ensure that all is good so we do not end up with many datasets to fixup later on?

**Comment by jwodder** [comment]
@yarikoptic Ran "verify" on some updated datasets successfully; re-enabled cronjob.

**Comment by yarikoptic** [comment]
Great , thanks!
