### ISSUE TITLE
Validate automated unembargo implementation in dandi-archive

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#51]
I do not see any open issue which states being blocked by absent ATM unembargo (TODO: edit this after discovered).

There is WiP on dandi-archive side to provide automated unembargo and it is out of Draft:

- https://github.com/dandi/dandi-archive/pull/1965

would be great to test against it before it gets merged/released so we do not play catch up later on.

**Comment by jwodder** [comment]
@yarikoptic PR #36 is blocked by the absence of unembargo, and it seems to count as a test thereof.  What exactly still needs to be done?

**Comment by yarikoptic** [comment]
make https://github.com/dandi/backups2datalad/pull/36 test against the version proposed in https://github.com/dandi/dandi-archive/pull/1965 -- would it be feasible? (I did not check how we deploy dandi-archive, might need extra step of pip install from that branch)

**Comment by jwodder** [comment]
@yarikoptic `backups2datalad` currently runs its tests against DANDI Staging directly.  You may be thinking of dandi-cli, which tests against a Dockerized version of the Archive, but even that is limited to the latest code on the Archive's master.

**Comment by yarikoptic** [comment]
oh, right, so we are doomed to wait until staging gets that PR merged - then we could test against.
