### ISSUE TITLE
Support embargoed dandisets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#8]
ATM we are completely skipping them. In the light of integration with github for issue tracking etc would be desired/needed.  In general it should not require much difference in behavior I think, but @jwodder please correct me if I am wrong. I see the need to:

- Created github repos would be created private
- For all assets populate only API URLs
  - @yarikoptic would need to look into how we should handle authentication. Likely the simplest way would be to provide (within DataLad) a "provider" configuration to provide the API Token in the request. 
  - I do not think we should populate direct URLs to private bucket ATM at all, in particular since embargo is being [redesigned](https://github.com/dandi/dandi-archive/pull/1772), but we could for "public assets" in embargoed datasets.
- If dandiset becomes unembargoed 
  - github repository should be made public if private
  - we should populate direct http URLs to S3 for all blobs  (worth adding a service command for that: given a dandiset id go through all assets and ensure presence of direct s3 http url)

Some related thoughts
- since dropbox backup is "private" anyways, no need to anyhow separate it out for embargoed content

@AlmightyYakob , a few questions:

- in the API ATM can we know if blob is embargoed or not -- from URL?
- after [embargo redesign](https://github.com/dandi/dandi-archive/pull/1772) how would we know that?
- do you have an example blob or just a URL to some key configured like [designed](https://github.com/dandi/dandi-archive/pull/1772/files#diff-f3d72d358571f346f0a3e26e3bf309127d6af6aac1e39f60e291b947d86eeb19R29) so that access would be denied -- I wonder if response would provide detail on how to authenticate to gain access. I.e. would it be 403 or [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) with useful WWW-Authenticate

**Comment by jwodder** [comment]
@yarikoptic 

* Can you provide the ID of a currently-embargoed repository?
* In order for the backup program to know when a Dandiset or asset becomes unembargoed, it needs to be able to determine whether a given Dandiset/asset backup was made while the API object was embargoed.  How should that be implemented?

**Comment by yarikoptic** [comment]
<details>
<summary>Here is a complete list</summary> 

```shell
❯ curl --silent -X 'GET' 'https://api.dandiarchive.org/api/dandisets/?page_size=1000&draft=true&empty=true&embargoed=true' -H 'accept: application/json' -H "Authorization: token $DANDI_API_KEY" | jq . | grep -e embargo_status -e identifier | grep -B1 EMBARG
      "identifier": "000224",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000234",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000240",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000242",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000248",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000253",
      "embargo_status": "EMBARGOED",
      "identifier": "000254",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000289",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000291",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000300",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000336",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000342",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000344",
      "embargo_status": "EMBARGOED",
      "identifier": "000345",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000352",
      "embargo_status": "EMBARGOED",
      "identifier": "000353",
      "embargo_status": "EMBARGOED",
      "identifier": "000354",
      "embargo_status": "EMBARGOED",
      "identifier": "000355",
      "embargo_status": "EMBARGOED",
      "identifier": "000356",
      "embargo_status": "EMBARGOED",
      "identifier": "000357",
      "embargo_status": "EMBARGOED",
      "identifier": "000358",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000360",
      "embargo_status": "EMBARGOED",
      "identifier": "000361",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000403",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000407",
      "embargo_status": "EMBARGOED",
      "identifier": "000408",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000450",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000459",
      "embargo_status": "EMBARGOED",
      "identifier": "000460",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000464",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000471",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000475",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000484",
      "embargo_status": "EMBARGOED",
      "identifier": "000485",
      "embargo_status": "EMBARGOED",
      "identifier": "000486",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000493",
      "embargo_status": "EMBARGOED",
      "identifier": "000526",
      "embargo_status": "EMBARGOED",
      "identifier": "000527",
      "embargo_status": "EMBARGOED",
      "identifier": "000528",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000531",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000533",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000553",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000562",
      "embargo_status": "EMBARGOED",
      "identifier": "000563",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000573",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000578",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000580",
      "embargo_status": "EMBARGOED",
      "identifier": "000581",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000616",
      "embargo_status": "EMBARGOED",
      "identifier": "000617",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000620",
      "embargo_status": "EMBARGOED",
      "identifier": "000621",
      "embargo_status": "EMBARGOED",
      "identifier": "000622",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000627",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000673",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000675",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000681",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000684",
      "embargo_status": "EMBARGOED",
      "identifier": "000685",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000690",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000697",
      "embargo_status": "EMBARGOED",
      "identifier": "000698",
      "embargo_status": "EMBARGOED",
      "identifier": "000699",
      "embargo_status": "EMBARGOED",
      "identifier": "000700",
      "embargo_status": "EMBARGOED",
      "identifier": "000701",
      "embargo_status": "EMBARGOED",
      "identifier": "000702",
      "embargo_status": "EMBARGOED",
      "identifier": "000703",
      "embargo_status": "EMBARGOED",
      "identifier": "000704",
      "embargo_status": "EMBARGOED",
      "identifier": "000705",
      "embargo_status": "EMBARGOED",
      "identifier": "000706",
      "embargo_status": "EMBARGOED",
      "identifier": "000707",
      "embargo_status": "EMBARGOED",
      "identifier": "000708",
      "embargo_status": "EMBARGOED",
      "identifier": "000709",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000720",
      "embargo_status": "EMBARGOED",
      "identifier": "000721",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000725",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000727",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000729",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000731",
      "embargo_status": "EMBARGOED",
      "identifier": "000732",
      "embargo_status": "EMBARGOED",
--
      "identifier": "000767",
      "embargo_status": "EMBARGOED",

```
</details>

> * In order for the backup program to know when a Dandiset or asset becomes unembargoed, it needs to be able to determine whether a given Dandiset/asset backup was made while the API object was embargoed.

When we create git repo (and subsequent updates), we can set  `dandi.dandiset.embargo-status` datalad config (so within `.datalad/config`) to correspond to above `embargo_status`. When we get to a new update and it is switching from stored EMBARGOED to OPEN [NB1], that is the moment to handle migration.

NB1: since .datalad/config -- we would need to commit it. But we would not know exact time point for when it happened. We should take time of the most recent commit I guess. May be later when audit is implemented (ref: https://github.com/dandi/dandi-archive/issues/525)

**Comment by jwodder** [comment]
@yarikoptic 

* Should embargoed dandisets be included as submodules in the dandi/dandisets repository?
* At what point should support for embargoed assets in partially-embargoed Dandisets be added?  Should it be included in the PR that implements this issue, or should it come later?
    * For embargoed assets in partially-embargoed Dandisets, should their metadata be included in `.dandi/assets.json`?
* Retrieving embargoed data will require a API key, which `backups2datalad` previously had no need for.
    * If no API key is provided explicitly (via an envvar, CLI option, or config option, depending on how we decide to implement passing it), should `backups2datalad` attempt to retrieve an API key from the keyring?  This would fail if the script is running unattended and the keyring requires a password.
    * If no API key is provided, should the script error?  Warn?  Silently only operate on non-embargoed data?  Should there be a command-line or config file option to control this behavior?

> I do not think we should populate direct URLs to private bucket ATM at all ... but we could for "public assets" in embargoed datasets.

What do you mean by "'public assets' in embargoed datasets"?

**Comment by yarikoptic** [comment]
> * Should embargoed dandisets be included as submodules in the dandi/dandisets repository?

good question: 

choice A: IMHO it would be ok to include them since we do not leak any metadata which might be sensitive. But it would be a discrepancy from website/API behavior of not showing them up at all unless authenticated/having access. 

choice B: For consistency we could

- not add them as submodules. To avoid addition/commit by mistake, let's add them to `.git/info/exclude`.
- upon unembargo -- remove from `.git/info/exclude` and add as submodules

I personally would prefer choice A since it would be less fragile.  @satra WDYT? 

> * At what point should support for embargoed assets in partially-embargoed Dandisets be added?  Should it be included in the PR that implements this issue, or should it come later?

If there is easy way to tell embargoed blob from public -- let's add right away since would be trivial.
If not -- later

>   * For embargoed assets in partially-embargoed Dandisets, should their metadata be included in `.dandi/assets.json`?

yes. Those repos will be private, so all good here

> * Retrieving embargoed data will require an API key, which `backups2datalad` previously had no need for.

yes, will need to be of one admin user. most likely we better gain a dedicated service user, wdyt @dandi/archive-maintainers -- do we have already a dedicated service user / API key?

>   * If no API key is provided explicitly (via an envvar, CLI option, or config option, depending on how we decide to implement passing it), should `backups2datalad` attempt to retrieve an API key from the keyring? 

sounds reasonable

> This would fail if the script is running unattended and the keyring requires a password.

how do we address that in any other testing scenarios?  IIRC we do use here a key already to staging for testing

>   * If no API key is provided, should the script error?  Warn?  Silently only operate on non-embargoed data?  Should there be a command-line or config file option to control this behavior?

As embargo is built-in functionality, for now we can just error out.  If later we run into use case to support cases without embargo, we will look into making it optional.

> * What should `backups2datalad` do if a Dandiset's `embargo_status` is `"UNEMBARGOING"`?  I believe that status means that the Dandiset is currently in the process of being updated from embargoed to open.

Skip update for it and re-consider on the next run

> > I do not think we should populate direct URLs to private bucket ATM at all ... but we could for "public assets" in embargoed datasets.
> 
> What do you mean by "'public assets' in embargoed datasets"?

My assumption was (I think  it might not correspond to how it actually works ATM): it is more of a "public blob" in an asset within embargoed dandiset:  if someone uploads a file which already exists in the archive publicly, we would just reuse blob from the public blobs pool.  Looking at DB models https://github.com/dandi/dandi-archive/blob/HEAD/dandiapi/api/models/asset.py#L137 I was expecting to have a different from `blob` `embargoed_blob` in the output of listing assets,

<details>
<summary>but looking at our "test development" embargoed dandiset where 1 blob also is present in public dandisets -- everything seems to be in embargoed bucket if I look at the details of the asset and the ContentURLs</summary> 

```shell
❯ curl --silent -X 'GET' 'https://api.dandiarchive.org/api/dandisets/000344/versions/draft/assets/' -H 'accept: application/json' -H "Authorization: token $DANDI_API_KEY" | jq .
{
  "count": 4,
  "next": null,
  "previous": null,
  "results": [
    {
      "asset_id": "4ec64802-d979-4917-b7f9-c025c9aeecb1",
      "blob": "bc2f5c33-6022-4249-807b-a6623793d3cf",
      "zarr": null,
      "path": "README.md",
      "size": 121,
      "created": "2022-10-10T19:16:58.431070Z",
      "modified": "2022-10-10T19:16:58.932418Z"
    },
    {
      "asset_id": "8f998a62-ac4c-465d-9989-656c90fb4668",
      "blob": "127efb7b-4261-4f91-80f3-43ba23f3f9f1",
      "zarr": null,
      "path": "sub-private/sub-private.dat",
      "size": 17,
      "created": "2022-10-10T19:16:58.509133Z",
      "modified": "2022-10-10T19:16:58.749121Z"
    },
    {
      "asset_id": "52830095-77e8-4ffe-9635-54ce9cb06567",
      "blob": "2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826",
      "zarr": null,
      "path": "sub-public/sub-public.nwb",
      "size": 18792,
      "created": "2022-10-10T19:17:07.870204Z",
      "modified": "2022-10-10T19:17:07.933219Z"
    },
    {
      "asset_id": "684c2229-c4f9-4f4f-91f6-6d55fa1603b9",
      "blob": "10d9c3e5-0caf-4a0b-8662-487e0cba85ce",
      "zarr": null,
      "path": "sub-random/sub-random_size-10M.dat",
      "size": 10485760,
      "created": "2022-10-10T19:19:47.573199Z",
      "modified": "2022-10-10T19:19:48.097682Z"
    }
  ]
}


❯ curl --silent -X 'GET' 'https://api.dandiarchive.org/api/dandisets/000344/versions/draft/assets/4ec64802-d979-4917-b7f9-c025c9aeecb1/' -H 'accept: application/json' -H "Authorization: token $DANDI_API_KEY" | jq .contentUrl
[
  "https://api.dandiarchive.org/api/assets/4ec64802-d979-4917-b7f9-c025c9aeecb1/download/",
  "https://dandiarchive-embargo.s3.amazonaws.com/000344/blobs/bc2/f5c/bc2f5c33-6022-4249-807b-a6623793d3cf"
]

```
</details>

so may be there is no mixed ones ATM. @AlmightyYakob can you clarify on current implementation?

**Comment by jwodder** [comment]
> >   * For embargoed assets in partially-embargoed Dandisets, should their metadata be included in `.dandi/assets.json`?
> 
> yes. Those repos will be private, so all good here

I assumed that partially-embargoed Dandisets would have an `embargo_status` of "OPEN", and thus their repositories would be public.

@AlmightyYakob How do/will partially-embargoed Dandisets (i.e., Dandisets in which not all assets are embargoed) work?  What is the `embargo_status` of such Dandisets?  How would a user of the API determine whether a given asset was embargoed?

> > [Fetching from the keyring] would fail if the script is running unattended and the keyring requires a password.
> 
> how do we address that in any other testing scenarios?  IIRC we do use here a key already to staging for testing

The `backups2datalad` testing key is provided solely as an environment variable; the keyring is never consulted.  In addition, dandi-cli tests only interact with the keyring when specifically testing keyring support.

> > > I do not think we should populate direct URLs to private bucket ATM at all ... but we could for "public assets" in embargoed datasets.
> > 
> > What do you mean by "'public assets' in embargoed datasets"?
> 
> My assumption was (I think  it might not correspond to how it actually works ATM): it is more of a "public blob" in an asset within embargoed dandiset:  if someone uploads a file which already exists in the archive publicly, we would just reuse blob from the public blobs pool.

How would such assets be identified?

**Comment by satra** [comment]
> I personally would prefer choice A since it would be less fragile. @satra WDYT?

if it's just a dandiset id, that's fine. if it's the tree layout, we shouldn't. we don't enforce that embargoed dandisets should be valid or anonymized explicitly at the moment.

@jwodder - currently there is no support for a partially embargoed dandiset (it's either embargoed or not). this is a feature that has been requested, which if implemented would result in multiple status at the dandiset level and asset level protection. we can change the backup actions when partially embargoed or restricted dandisets are implemented. 

as @yarikoptic noted a public blob can be added to an embargoed dandiset, but that blob should remain in the public bucket till modified.

**Comment by yarikoptic** [comment]
@satra 

> > I personally would prefer choice A since it would be less fragile. @satra WDYT?
> 
> if it's just a dandiset id, that's fine. if it's the tree layout, we shouldn't. we don't enforce that embargoed dandisets should be valid or anonymized explicitly at the moment.

yeap -- just dandiset id, and possible its datalad dataset ID. Ok, then let's proceed with the simpler A.

> as @yarikoptic noted a public blob can be added to an embargoed dandiset, but that blob should remain in the public bucket till modified.

that is what I thought but not sure if that "can" is really implemented -- according to collapsed demo in [my comment above](https://github.com/dandi/backups2datalad/issues/8#issuecomment-1857237342) even that publicly available blob is said to be available from embargoed bucket, not the main one.

I will let @AlmightyYakob to clarify on @jwodder's questions.

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob How do/will partially-embargoed Dandisets (i.e., Dandisets in which not all assets are embargoed) work? What is the `embargo_status` of such Dandisets?

The questions you're asking are a great example of why an embargo re-design is needed. At the moment, there is very little restriction on what is allowed. Indeed dandisets can have mixed embargoed/open assets, and the dandiset containing these mixed assets could be either embargoed or open.

> How would a user of the API determine whether a given asset was embargoed?

The only way you _could_ really do so is by looking at the `access` metadata field on the asset itself, which should be either `dandi:OpenAccess` or `dandi:EmbargoedAccess`. However, due to the faults of our current implementation, that can't be relied on. Just messing around to answer this question, I exclusively found example of embargoed asset blobs that pointed to an asset with an `access` field of `dandi:OpenAccess`.

**Comment by jwodder** [comment]
@yarikoptic Taking @AlmightyYakob's comment above into account, how should assets with different embargo states from their Dandisets be handled?

**Comment by yarikoptic** [comment]
ok, for now let's not discriminate between different kinds of assets -- and for an embargoed dandiset populate only with API urls.

**Comment by jwodder** [comment]
For reference, a summary of what needs to be done for this issue:

- `backups2datalad` should now always require an API key to be provided via the methods supported by `DandiAPIClient::dandi_authenticate()`
- Retrieval of all Dandisets from the API should now set `embargoed=true` (Due to https://github.com/dandi/dandi-archive/pull/1790)
- If a Dandiset has an `embargo_status` of `UNEMBARGOING`, skip operating on it for the current run.
- If a Dandiset has an `embargo_status` of `EMBARGOED`:
    - Set `dandi.dandiset.embargo-status` in `.dandi/config` to `EMBARGOED`
    - The GitHub repository for the Dandiset and any Zarrs within it should be private upon creation
    - Only register API URLs for assets & Zarr entries, not S3 URLs
    - The dataset should still be added as a submodule to dandi/dandisets
- If a Dandiset has an `embargo_status` of `OPEN` and `dandi.dandiset.embargo-status` in `.dandi/config` is `EMBARGOED`:
    - Register S3 URLs for all assets and Zarr entries
        - Add a service command for doing just this
    - Set `dandi.dandiset.embargo-status` in `.dandi/config` to `OPEN`
        - When committing this change (if there were no other changes?), set the commit's author date to the same value as for the previous commit to the Dandiset
    - Make the GitHub repository for the Dandiset and any Zarrs public

(Yes, I'm aware that embargoed Dandisets currently can't contain Zarrs, but extending the logic to Zarrs right away shouldn't be that hard and is a good idea.)

@yarikoptic Is this all correct?

Side note: I'm assuming that an open Dandiset cannot be converted to (fully) embargoed.  Is that currently correct?  Will it remain correct after the redesign?  CC @jjnesbitt

**Comment by jwodder** [comment]
@yarikoptic I've created a separate issue for supporting partiall-embargoed Dandisets later at #10.

**Comment by yarikoptic** [comment]
Overall looks great, thank you. A few clarifications:

> * Set `dandi.dandiset.embargo-status` in `.dandi/config` to `EMBARGOED`

in `.datalad/config` not `.dandi/config`

> * Only register API URLs for assets & Zarr entries, not S3 URLs

As embargo support is still being worked out and changing, and there is even no design for zarr embargo and I don't think we even have API to provide access to embargoed zarrs entries --  just error out if encountering zarr entry in embargoed dataset as should not happen ATM.  That would also simplify implementation as would not need recurse into zarrs to populate URLs and making zarrs public in the last item.

**Comment by jwodder** [comment]
@yarikoptic How exactly do you want the API key to be provided when running the backup script?  As an environment variable, on the command line, in the config file, via the keyring, what?  Note the following:

* `backups2datalad` uses a custom async client rather than `DandiAPIClient`, so it does not have the latter's keyring authentication methods
* Currently, keyrings are not involved at all while testing `backups2datalad`
* Reliance on keyrings could be a problem when `backups2datalad` is run unattended if the keyring happens to need a password
    * `dandi-cli`'s keyring code also requires user interaction if the keyring lacks an API key, if the key is invalid, or if the default keyring fails

**Comment by yarikoptic** [comment]
I am ok with just relying on `os.environ.get("DANDI_API_KEY", None)` for now.

**Comment by yarikoptic** [comment]
May be for clarity and consistency on a separate commitment would be better. Might be even worth tagging it (eg `unemargoed`, just lightweight not annotated) to simplify introspection etc

**Comment by jwodder** [comment]
@yarikoptic What git-annex command do I use to query whether a key exists in the repository's `HEAD`?

**Comment by yarikoptic** [comment]
One key at a time? What do we need it for?

**Comment by jwodder** [comment]
@yarikoptic 

> One key at a time?

Preferrably batched, if possible.

> What do we need it for?

When a Dandiset is unembargoed, `backups2datalad` needs to register the S3 URL for each asset with the corresponding entry in the backup repository, and `git-annex registerurl` operates on keys.  If the code were to try to register a URL on a key that's not in the repository — say, if an asset were added to the Dandiset in the Archive since the last time `backups2datalad` ran — `registerurl` would fail, so we need to check whether an asset's key is in the repository before trying to register a URL for it.  Note that trying to implement this by checking whether the asset path exists wouldn't work in situations where an asset's blob was modified since the last time `backups2datalad` ran, as then we'd be registering the URL for the new blob on a file referring to the old blob.

**Comment by yarikoptic** [comment]
so, overall, we need to get through all annexed files in the HEAD tree and `registerurl` them, correct?

if `datalad` api was used, then smth like `datalad -f json_pp status --annex basic` (`ds.status(annex='basic')` in python I assume) would have returned records for all the files with the annexed ones having keys listed.   Underneath it uses `find` so equivalent command would `git annex find --format='${key}\n' --include '*'` to list the keys, just take a unique set of them since I guess would repeat for duplicated content.

**Comment by jwodder** [comment]
@yarikoptic

> so, overall, we need to get through all annexed files in the HEAD tree and `registerurl` them, correct?

Correct.

Moving on to a related aspect: Checking keys requires getting assets' SHA256 digests from the Archive.  What should the "S3 URL registration routine" do if the Archive hasn't finished digesting an asset?  For comparison, the normal asset-syncing code (which, for various reasons, the new routine is separate from) logs a message when this happens and doesn't download any further assets.

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
> What should the "S3 URL registration routine" do if the Archive hasn't finished digesting an asset? For comparison, the normal asset-syncing code (which, for various reasons, the new routine is separate from) logs a message when this happens and doesn't download any further assets.

sounds like keeping the same behavior would be logical here as well, WDYT?
